### ISSUE TITLE
Rerunning mob_init re-downloads the data

### ISSUE THREAD

**Issue by tseemann** [phac-nml/mob-suite#10]
This is probably desired behaviour, but maybe if you make the install instructions make people run `mob_init`, or `mob_typer` could check if the data is there and tell me to download it by running `mob_init` if it is not there?

**Comment by jrober84** [comment]
Both mob_recon and mob_typer check for the presence of the databases and then will run mob_init if that fails. I have tested this on Centos 7 and Mac OSX High Sierra, what environment are you running this on? One potential issue could be in using slurm to run the jobs, mob_init will request by default all of the threads available on a machine to a limit of 32. This could cause issues on an HPC and theoretically multiple jobs without the databases setup will cause multiple mob_inits to run.  I will update the first run instructions for those looking to run it on an HPC.

**Comment by tseemann** [comment]
I am not using slurm. Just a single Centos 7 system with 72 cores.

I said if i ran `mob_init` again it re-downloads. If that's expected behaviour we can close this. It makes sense it probably should.
