### ISSUE TITLE
Is --run_typer ignored in mob_recon?

### ISSUE THREAD

**Issue by rpetit3** [phac-nml/mob-suite#100]
Hello! 

While running `mob_recon` I'm getting the `mobtyper_results.txt` without giving the parameter `--run_typer`. Is this the expected behavior?

Don't get me wrong I like it that way! Just a little confused

Cheers,
Robert

**Comment by jrober84** [comment]
Sorry about the confusion, that option is a legacy carry over. It will be removed in the next version.

**Comment by rpetit3** [comment]
Ahh, no worries! Thanks for the follow up
