### ISSUE TITLE
Maximum Contig Size for MOB-recon?

### ISSUE THREAD

**Issue by schorlton** [phac-nml/mob-suite#101]
Thanks for the great software! I'm wondering if the `--max_contig_size` param is implemented?
https://github.com/phac-nml/mob-suite/blob/1d735b30053b45457a59c277c8d996ab86e0347c/mob_suite/mob_recon.py#L63-L65

I couldn't find it  in the code if so. Just hit a case where we classified a complete circular 1+Mb bacterial genome as a novel plasmid. Thanks!

Addendum: also wondering about `--max_plasmid_size` (couldn't find it either):
https://github.com/phac-nml/mob-suite/blob/39317225fcbd0a98fd1f1bd663d91932ae0fae8e/mob_suite/mob_recon.py#L66-L68

**Comment by jrober84** [comment]
Thanks for pointing that out, yes both of those options were orphaned in the update, I have added back in their functionality as quality checks and they will be available in the new version. Very cool you are finding plasmids that size, I know Borellia can have large plasmids nearing that size.

**Comment by schorlton** [comment]
Thanks!
*should not be finding plasmids that size - as per issue "we classified a complete circular 1+Mb bacterial genome as a novel plasmid" and I want to avoid this with the max size parameter!

**Comment by jrober84** [comment]
Ah ok, understood!
