### ISSUE TITLE
Docker Image Size

### ISSUE THREAD

**Issue by pbelmann** [phac-nml/mob-suite#102]
Hi,

thank you for this tool!
Your docker image with 4.71GBs of size is quite large.
I guess the reason for this is that your databases are part of the image.

Is there any way that you provide a second docker image that does not
download all databases?

**Comment by kbessonov1984** [comment]
Hi, 
The image is indeed large due to use of taxonomy database inside. Other option is to have databases folder mounted in the docker image to avoid long initialization inside the container each time you boot the image.  We will create a light image. What is the reason for a smaller image size use case?

**Comment by pbelmann** [comment]
Well in my case the system I'm using for running my pipeline has just 20GB of disk space on the root partition. If run a pipeline with multiple docker images, then there is not enough space left.
I agree that mounting your databases (which are in my case on a different partition) to a container is the way to go. Thanks! I'm looking forward to your lightweight image.

**Comment by kbessonov1984** [comment]
Hello,
Lite image of MOB-Suite v3.0.3 with tag `kbessonov/mob_suite:3.0.3_lite` without initialized databases is available on the DockerHub resource. You can pull it (`docker pull kbessonov/mob_suite:3.0.3_lite`) and run it `docker run --rm -v $(path2databases_dir):/mnt/databases  mob_recon docker pull kbessonov/mob_suite:3.0.3_light mob_recon -i assembly.fasta -o outdir_name --database_directory /mnt/databases`. To run make sure you mount the directory with databases so `mob_init` routine would not be triggered.

**Comment by pbelmann** [comment]
Awesome! Thanks!
