### ISSUE TITLE
Enhancement: Don't fix threads to 1?

### ISSUE THREAD

**Issue by schorlton** [phac-nml/mob-suite#104]
Hi,

Thanks again for your support of MOB-Suite! It seems like threads are fixed to 1 for a bunch of functions in [mob_recon.py](https://github.com/phac-nml/mob-suite/blob/mob-3.0.3/mob_suite/mob_recon.py)...I'm wondering if there's a reason for this? We're hitting speed limitations of `tblastn` on large metagenomic assemblies. I'd even be happy to open a PR to set them to `num_threads` if it makes sense. Thanks!

Sam

**Comment by jrober84** [comment]
v. 3.1.0 removes this limitation of threads to 1. Older versions of tblastn had issues with higher thread counts but this isn't a problem anymore.
