### ISSUE TITLE
How to specify -p and -t arguments in mob cluster without any information

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [phac-nml/mob-suite#120]
Hi, I managed to install the MOBsite via pip.

Now I have some other problem.

We have one fasta file containing 50 random plasmid sequences. Nothing else is known about plasmids.

We want to cluster the plasmid sequences. We use command mob_cluster, we put the fasta file as infile, but what do we put as the -p and the -t? it wont run without the two arguments.

Thanks

**Comment by Abelcanc3rhack3r** [comment]
We are just trying to cluster the plasmids with each other, not necessarily with other known plasmids in a database

ok, I wil run the mob typer and share with you the results when we get them

**Comment by luciagrami** [comment]
Hello, 

I run MOB typer on the new set of plasmids, but no sure how to create the taxonomy file, and also I couldn't find a sample file, so not sure how the taxonomy file looks like.

Thanks!

**Comment by jrober84** [comment]
I will update the documentation for MOB-cluster to improve it as there are few details available currently in the repo. But in the meantime, the taxonomy file is just a two column tab-delimeted file with the header id,organism. Where id is the sequence id of your plasmids you wish to add to your database and organism is the complete name that you want to associate with your sequence. The organism name must be present in the NCBI taxonomy for it to work correctly.

**Comment by luciagrami** [comment]
Thanks!
