### ISSUE TITLE
module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by yqy6611** [phac-nml/mob-suite#123]
Hi all, after updating numpy I encountered this error message:

**AttributeError: module 'numpy' has no attribute 'bool'**, as well as 

**FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.**

Any ideas on how to fix this?

**Comment by jchorl** [comment]
Fwiw this appears to be the same as https://github.com/NVIDIA/TensorRT/issues/2557

Pinning to 1.23 should work. However it appears the README build process is broken at the moment, and I didn't have time to chase that down, so couldn't cut a PR.

**Comment by jrober84** [comment]
I am preparing release v 3.1.1 which will restrict numpy version to < 1.23.5 to prevent this issue
