### ISSUE TITLE
Input fasta file

### ISSUE THREAD

**Issue by Wendy361** [phac-nml/mob-suite#124]
Hi, 
I was wondering if mob-recon can accept fasta files from hybrid assembly. For each isolate, we did the both nanopore and illumina sequence and we used unicycler to assemble the nanopore and illumina fastq files for each isolate.

**Comment by jrober84** [comment]
MOB-recon can accept draft or complete assemblies.  It is much easier to work with complete plasmids than draft ones. There are a few caveats to be aware of.  If your assemblies are complete, then there isn't really a need for reconstruction, you could just run mob-typer on everything but the chromosome.  So there is no harm in running MOB-recon but it isn't necessary
