### ISSUE TITLE
False plasmid found in the plasmid reference database

### ISSUE THREAD

**Issue by davidtong28** [phac-nml/mob-suite#126]
Hi!
I have been using mobsuite to detect plasmids in some Campylobacter strains. I noticed that a cluster, AG887, was detected in all (~ 300) my C. jejuni isolates. I looked into this and found that the reference it is using (CP023447) contains Campylobacter core genes (Cj0031 ~Cj0143c) which were used in Campylobacter cgMLST. I am suspecting that the reference might be incorrectly marked as plasmid by the submitter and used in the reference database. I'm wondering the possibility of this being a false plasmid.
Cheers!
David

**Comment by davidtong28** [comment]
Update: The GFA files provided by the assembler also show that the AG887 plasmids also does not form a loop, but connected to the chromosome

**Comment by jrober84** [comment]
Thank you for the information, I have marked this plasmid as something to investigate for the next release of the MOB-suite database. I don't currently have a timeline on when a new DB will be released but MOB-suite does have a feature that you can give it sequences that you want to exclude from being classified as being a plasmid. You can provide the sequence for this element in your run and it will exclude it from being classified as a plasmid. This should let you continue your analysis without needing to wait on a new DB. Alternatively, if you are comfortable, you can edit the very large fasta file of plasmids and remove the accession from it and then rebuild the blast-db.

**Comment by davidtong28** [comment]
Thank you for your response. I was wondering if predicted plasmids are allowed to have no hallmark features (only sequence similarity), and if so, is there a filtering option in Mobsuite that could filter them out?
Thanks!

**Comment by jrober84** [comment]
Presence of replicon, relaxase is not required to label a sequence as a plasmid. However, it would need to have overlap with the closed plasmid database or identified as circular. The following configurations are possible
1) Rep+, MOB+, PlasmidDB+, Circular+
2) Rep+, MOB+, PlasmidDB-, Circular+
3) Rep+, MOB+, PlasmidDB-, Circular-
4) Rep-, MOB-, PlasmidDB+, Circular+
5) Rep-, MOB-, PlasmidDB+, Circular-
