### ISSUE TITLE
only one instance will run at the same time

### ISSUE THREAD

**Issue by ChristyPeterson** [phac-nml/mob-suite#13]
When submitting more than one instance of mob-recon, the following error is given:
ERROR:root:Error needed database missing "_conda/envs/__mob_suite@1.4.8/lib/python3.6/site-packages/mob_suite/databases/repetitive.dna.fas.nin"

I think its because when you run repetitive_blast it is rebuilding the blast database every time even when using a built in database.

**Comment by kbessonov1984** [comment]
Hello. Does it happen with the Galaxy wrapper or when `mob_recon` is run in a command line in parallel? Could you possibly share a dataset (i.e. input fasta files) which gives you such an error so that we can try to replicate it on our end? Thank you very much for letting us know.

**Comment by ChristyPeterson** [comment]
Its on the galaxy wrapper. I can send you a couple of the fasta's via the
corporate email system since they are unpublished at the moment.

-Christy

**Comment by ChristyPeterson** [comment]
I just tried to run the same set of 495 samples on the command line and
while most finished I did get the same error with a smaller number. So I
believe the problem is happening on the command line as well as the galaxy
wrapper. Just on the galaxy wrapper they conflict more often than on cmd
line.

**Comment by ericenns** [comment]
Hi @kbessonov1984 I helped @ChristyPeterson debug this error and it will occur on the cmd line or through galaxy. The cause of the error is this line specifically.
https://github.com/phac-nml/mob-suite/blob/master/mob_suite/mob_recon.py#L306
and
https://github.com/phac-nml/mob-suite/blob/master/mob_suite/utils.py#L194

Basically everytime the method repetitive_blast is invoked the repetitive database is being rebuilt with blast. So when multiple instances are being run at the same time, https://github.com/phac-nml/mob-suite/blob/master/mob_suite/mob_recon.py#L431 throws an error if it is checking for the blast db when it is currently being regenerated.

**Comment by jrober84** [comment]
Thanks @ericenns for the help on pinning down the error, the database does not need to be built each time and I have updated the code to remove that. The pip package has been updated and the conda package will be updated soon.

**Comment by jrober84** [comment]
@kbessonov1984 has updated the conda package so this issue should be resolved
