### ISSUE TITLE
NamesToTaxIDs() missing 1 required positional argument: 'ETE3DBTAXAFILE'

### ISSUE THREAD

**Issue by k-krakowski** [phac-nml/mob-suite#132]
Running mob_cluster command results in: `NamesToTaxIDs() missing 1 required positional argument: 'ETE3DBTAXAFILE'`.
The error is in mob_cluster.py in line 528 -> taxids = NamesToTaxIDs(organisms)
You can add ETE3DBTAXAFILE into constants.py, import it in utils.py and remove ETE3DBTAXAFILE from all functions arguments in utils.py. That should solve this issue.

**Comment by ggl2151** [comment]
Hello, I also encountered the same problem, but I don't know how add ETE3DBTAXAFILE into constants.py. Is it like this.
ETE3DBTAXAFILE = os.path.abspath("/home/guest504/miniconda3/lib/python3.8/site-packages/mob_suite-3.1.4-py3.8.egg/mob_suite/databases" + "/taxa.sqlite") 
Next, I entered 'from mob_suite.constants import ETE3DBTAXAFILE' in the utils.py
Last, I want to remove ETE3DBTAXAFILE from all functions arguments in utils.py.  But I found that there are too many ETE3DBTAXAFILEs in the utils.py, and I don't know how to delete them. Should I just delete the ETE3DBTAXAFILE string or should I also delete its related functions.I would be very grateful if you could answer.

**Comment by ggl2151** [comment]
Yep, that fixed it. Thank you sir!  
Also, let me remind my partner who has the same problem as me to pay attention to a small issue, NamesToTaxIDs(names,ETE3DBTAXAFILE)  function located in mob_cluster.py on line 528.

**Comment by jrober84** [comment]
The code update has been incorporated into MOB-cluster and will be part of the next release
