### ISSUE TITLE
Bioconda Pacakge - Allow Python <3.6

### ISSUE THREAD

**Issue by lowandrew** [phac-nml/mob-suite#14]
Would it be possible to modify the bioconda package to allow for python versions <3.6? I've got a few pipelines that are stuck on 3.5, so I have to manually install mob_suite instead of just grabbing everything from conda the way I'd like to.

I've attached a version of the `meta.yaml` (as `meta.yaml.txt`, since apparently github won't allow .yaml file to be attached to issues) that would allow for python >= 3.4 to work, instead of only python >=3.6.

Thanks!

 
[meta.yaml.txt](https://github.com/phac-nml/mob-suite/files/2608733/meta.yaml.txt)

**Comment by kbessonov1984** [comment]
Hello, Andrew,
Yes, it is not a problem at all. MOB-Suite works with any python3 version. Sorry for this oversight. Will downgrade to python 3.4 and release a new package build in a couple of days. Thanks for reaching to us. We are always glad to help.

Kirill

**Comment by lowandrew** [comment]
Perfect, thanks!

**Comment by kbessonov1984** [comment]
Hi, Andrew. I've finally updated recipe on the bioconda repository as per your request. The build number is 1. The version number did not change and is still 1.4.9. In a couple of hours the bioconda should update repository with the new code version. Best wishes in your work!

**Comment by kbessonov1984** [comment]
If no-arch installation does not work from the bioconda repository. Try our personal repository by running. Thanks!
```
conda install -c kbessonov mob_suite
```
