### ISSUE TITLE
mob_init - first run - database download error

### ISSUE THREAD

**Issue by motroy** [phac-nml/mob-suite#15]
Hi,
Just installed mob-suite. 
Found that the database was not downloading when running mob_init.
The download URL (https://ndownloader.figshare.com/articles/5841882?private_link=a4c92dd84f17b2cefea6) was not accessible (also mentioned in the README). 
replaced with this address: https://ndownloader.figshare.com/articles/5841882/versions/1
now seems to work.
Hope this helps,

**Comment by jrober84** [comment]
Thanks to @lowandrew for making the changes, the code has been updated with the new url

**Comment by eacton** [comment]
This should be changed on the landing page as well - the database download did not work for me with the conda install and I tried downloading the database manually with the landing page url, which did not work. Might as well save some headaches.

**Comment by kbessonov1984** [comment]
@eacton will be updating conda package next week and change database remote host. The database download url change was unexpected and we apologize for inconveniences. Thank you for reporting this as it allows us to follow up asap.
