### ISSUE TITLE
mob_recon does not reconstruct plasmids sequences

### ISSUE THREAD

**Issue by maricleon** [phac-nml/mob-suite#158]
I am encountering an issue with the reconstruction of plasmid sequences using mob_recon. While all other files are successfully generated, the actual sequences remain absent. The recurring warning message I receive suggests a potential cause for this problem. Despite thoroughly checking my Blast installation and finding it apparently in order, the issue persists.

2024-01-20 10:06:39,240 root WARNING: No BLASTN results to parse from file test/__tmp/orit_blast_results.txt [in /home/company/leomar1/program_files/miniconda3/envs/tools/lib/python3.11/site-packages/mob_suite/blast/__init__.py:181]

**Comment by kbessonov1984** [comment]
Hi,
There might be no contigs identified of plasmid origin but rather chromosomal. Plasmid contigs are identified by looking to key markers such as oriT, mpf, replicon, MOB allele sequences. If no plasmid contigs are found, no plasmid FASTA files are generated. If you could provide an example input file, then we could further help you.
For plasmid identification logic and contig filtering you can check the source code [here](https://github.com/kbessonov1984/mob-suite/blob/1400ab41cdc586fafa838dd896532b0a17754b5a/mob_suite/mob_recon.py#L1156)
