### ISSUE TITLE
Several hundred plasmids relaxase typed as 'MOBP' are now typed as '-'

### ISSUE THREAD

**Issue by e-jkl** [phac-nml/mob-suite#171]
Hi there, I ran a run on the same plasmids using version 3.1.9, which I had previously run using version 3.1.5. I ran this on about a thousand plasmids. However, I have gotten several hundred plasmids which mainly were previously typed as 'MOBP' but are now typed as '-'. I checked the /lib/python3.8/site-packages/mob_suite/databases/mob.proteins.faa of both versions I had installed, but the files are exactly the same.

Could this be anything to do with the filtering of Blast results in the newer version, since the original database files are the same?

Thank you so much.

**Comment by e-jkl** [comment]
As MOB-suite couldn't be installed via conda, pip was used as per https://github.com/phac-nml/mob-suite/issues/169.

The following commands were used.

conda create -p MOB_SUITE_3.1.9_ENV
conda activate MOB_SUITE_3.1.9_ENV
conda install python=3.8 
pip3 install mob_suite
conda install mash=2.3
conda install blast=2.9.0
mob_init

My first attempt did not specify the Blast and Mash versions, and the Blast version turned out to be 2.5.0. For the versions of Blast and Mash here, they were taken from https://github.com/phac-nml/mob-suite/blob/6cd3f98686e140914ad4d87112b21dee8ead4804/mob_suite/conda/meta.yaml#L32. 

The next attempt with the corrected Blast version resulted in a reduction of more than a hundred of the untyped plasmids, but untyped plasmids were still in the range of hundreds ultimately. 

Hence, it is possible this is a Blast compatibility issue. 

Is the current installation strategy correct, since the conda installation is not working?

**Comment by kbessonov1984** [comment]
We had found that the BLAST version installed has a major impact on results. Make sure that your both MOB-Suite versions <ins>use the same BLAST version</ins> for consistency. We do not recall any major code changes between versions 3.1.5 and 3.1.9. See if you install the same BLAST version in MOB-Suite v3.1.9 environment as in the MOB-Suite v3.1.5 environment and get the MOBP hits.

**Comment by e-jkl** [comment]
@kbessonov1984 Thank you so much. I have changed the BLAST version to 2.14.0 which was installed as part of 3.1.5 (using conda then), and was able to get the same relaxase types when running 3.1.9. 

Do note, however, that the conda installation route is still broken as of yesterday - the 3.1.9 installation was done via pip as stated in https://github.com/phac-nml/mob-suite/issues/171#issuecomment-2322846665, and then installing mash and blast additionally.
