### ISSUE TITLE
mob_init does not work

### ISSUE THREAD

**Issue by pavlo888** [phac-nml/mob-suite#18]
Hi, 

I have been able to successfully download the database from the provided link. However, when I run the command %mob_init, I get the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/mob_init", line 7, in <module>
    from mob_suite.mob_init import main
  File "/usr/local/lib/python3.7/site-packages/mob_suite/mob_init.py", line 3, in <module>
    import os, pycurl, tarfile, zipfile, gzip, multiprocessing, sys
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libcrypto.1.1.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so
  Reason: image not found

I am not sure what to do with this issue. 

Thank you in advance for your help.

Regards, 
Pablo

**Comment by kbessonov1984** [comment]
Hi Pavlo,
I am currently releasing a new conda package (hopefully this coming Friday) which will solve the pending issues on the automatic database download and addition of new parameters to specify location of databases if you already downloaded database on your own. However your issue seems to be more related with the `pycurl` library import. Try to re-install it and check that you can run `import pycurl`. We recommend running mob-suite in the conda environment to make sure all dependencies are properly installed. Try to run`conda install -c anaconda pycurl`. Let us know how it goes.

**Comment by kbessonov1984** [comment]
The new version 1.4.9.1 deposited on bioconda channel (https://anaconda.org/bioconda/mob_suite) was recently released that automatically runs `mob_init` script downloading the reference database files from the new set of mirrors.

**Comment by qianxin-kxy** [comment]
> The new version 1.4.9.1 deposited on bioconda channel (https://anaconda.org/bioconda/mob_suite) was recently released that automatically runs `mob_init` script downloading the reference database files from the new set of mirrors.

### Hello, I installed the software through the following code, but there are also similar errors. I don't know how to solve them
$ micromamba install -c bioconda mob_suite

File "/data/users/kxy/micromamba/envs/mob_suite_1/bin/mob_init", line 7, in <module>
    from mob_suite.mob_init import main
  File "/data/users/kxy/micromamba/envs/mob_suite_1/lib/python3.8/site-packages/mob_suite/mob_init.py", line 3, in <module>
    import os, pycurl, tarfile, zipfile, gzip, multiprocessing, sys
ImportError: /data/users/kxy/micromamba/envs/mob_suite_1/lib/python3.8/site-packages/pycurl.cpython-38-x86_64-linux-gnu.so: undefined symbol: curl_global_sslset
**I tried to the following methods to upgrade pycurl**

$ pip install --upgrade pycurl
Requirement already satisfied: pycurl in ./micromamba/envs/mob_suite_1/lib/python3.8/site-packages (7.45.1)
Collecting pycurl
  Downloading pycurl-7.45.2.tar.gz (234 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.2/234.2 kB 29.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py) ... done
  Created wheel for pycurl: filename=pycurl-7.45.2-cp38-cp38-linux_x86_64.whl size=142414 sha256=7631260e26aa09416f8cd6e17ecb6831e5436c9584c05bc795fcc0c102f0bd7c
  Stored in directory: /data/users/kxy/.cache/pip/wheels/07/65/79/9497b682fcb877281b1600e6580f5a9627bed14d29c361ecaa
Successfully built pycurl
Installing collected packages: pycurl
  Attempting uninstall: pycurl
    Found existing installation: pycurl 7.45.1
ERROR: Cannot uninstall 'pycurl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
**Tried again**
(mob_suite_1) [kxy@zju ~]$ pip install --force-reinstall pycurl
Collecting pycurl
  Using cached pycurl-7.45.2-cp38-cp38-linux_x86_64.whl
Installing collected packages: pycurl
  Attempting uninstall: pycurl
    Found existing installation: pycurl 7.45.1
ERROR: Cannot uninstall 'pycurl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
**I tried to run the code directly regardless of the error, but there was no result file**
$ mob_typer --infile /data/users/kxy/kxytry/assembleddata/tog_sample_year_ST/infile/ab_2012_ST195_6779.fasta --out_file sample_mobtyper_results.txt
Traceback (most recent call last):
  File "/data/users/kxy/micromamba/envs/mob_suite_1/bin/mob_typer", line 7, in <module>
    from mob_suite.mob_typer import main
  File "/data/users/kxy/micromamba/envs/mob_suite_1/lib/python3.8/site-packages/mob_suite/mob_typer.py", line 7, in <module>
    import mob_suite.mob_init
  File "/data/users/kxy/micromamba/envs/mob_suite_1/lib/python3.8/site-packages/mob_suite/mob_init.py", line 3, in <module>
    import os, pycurl, tarfile, zipfile, gzip, multiprocessing, sys
ImportError: /data/users/kxy/micromamba/envs/mob_suite_1/lib/python3.8/site-packages/pycurl.cpython-38-x86_64-linux-gnu.so: undefined symbol: curl_global_sslset
