### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by RoxanaZamudio** [phac-nml/mob-suite#23]
I have issue to run mob_recon. Below is the error message:
```
usage: mob_recon [-h] [-d DATABASE_DIRECTORY]
mob_recon: error: unrecognized arguments: -o /hpc-home/zamudio/mob_cluster --run_typer -n 32 -i /hpc-home/zamudio/sample.fasta
```
Am I using wrongly the flags for the input file and the output directory? 
Many thanks
Roxana

**Comment by kbessonov1984** [comment]
Hi, Roxana, 
Could you please paste entire command that you are trying to lunch in bash? I will allow me to investigate further.  
Also let us know what `mob_suite`  version are you running (e.g. latest commit or bioconda, etc.)?

You can try out by running `mob_recon` using the test data from this repository as follows
```
cd mob_suite/tests/TestData/Pseudomonas/test
mob_recon -i C0646_S111.contigs.fasta  -n 4 -o test
```

Let us know how it goes so that we can resolve issue together.

**Comment by RoxanaZamudio** [comment]
Dear Kirill,
Many thanks for your advice.
Below is the entire command that I used. I created a image by using singularity. Do you think that it can be a problem? Also, I am running in the slurm system.
```
singularity exec /hpc-home/zamudio/mob_suite/mob_suite.img mob_recon -d /hpc-home/zamudio/mob_suite/5841882 -i /hpc-home/zamudio/mob_suite/input/sample.fasta -n 4 -o /hpc-home/zamudio/mob_suite/test
usage: mob_recon [-h] [-d DATABASE_DIRECTORY]
mob_recon: error: unrecognized arguments: -i /hpc-home/zamudio/mob_suite/input/sample.fasta -n 4 -o /hpc-home/zamudio/mob_suite/test
```
I tried to run the test data but there is not such example in the github (mob_suite/tests/TestData/Pseudomonas/test).

The version of the mob_suite is 1.4.9.1.

Thank you in advance for your help.
Roxana

**Comment by kbessonov1984** [comment]
Hi, Roxana,
I've tried to run `mob_recon` on my end with your command line arguments and it worked well. I think the issue is that the container which is running `mob_typer` is not parsing arguments correctly. Try to login in interactive mode to your container via `singularity shell /hpc-home/zamudio/mob_suite/mob_suite.img`. Once inside the container lunch `mob_recon`. 
How `mob_suite` is installed inside the container? Is it running in conda environment or installed from github repo via `pip`?

**Comment by RoxanaZamudio** [comment]
Hi Kirill,
The `mob_suite` was installed in the HPC-cluster using the command `singularity build mob_suite.img docker://quay.io/biocontainers/mob_suite:1.4.9.1--py_0`

I followed your suggestion and the problem remain the same:
```
singularity shell /hpc-home/zamudio/mob_suite/mob_suite.img
Singularity: Invoking an interactive shell within container...

<utdir /hpc-home/zamudio/mob_suite/test --infile /hpc-home/zamudio/mob_suite/sample.fasta -d /hpc-home/zamudio/mob_suite/5841882                      
usage: mob_recon [-h] [-d DATABASE_DIRECTORY]
mob_recon: error: unrecognized arguments: --outdir /hpc-home/zamudio/mob_suite/test --infile /hpc-home/zamudio/mob_suite/sample.fasta
```
However I installed the `mob_suite` in my imac using `pip install mob_suite` and it is working. I am using the ` ncbi_plasmid_full_seqs.fas` database. This database is the standard one for plasmid identification?

Many thanks
Roxana

**Comment by kbessonov1984** [comment]
Hi Roxana,
I've did a bit of manual testing using docker image that you've cited before and all worked well. However when the same image was run through Singularity 3.2.0 for Macs and it gave me the same error `mob_recon: error: unrecognized arguments: -i test.fasta -o SRR3703080`. I will try to build an image with singularity using our new mob_suite version 2.0 and let you know.

For now here are instructions on how to execute command using `docker run`

1. Pull the container `docker pull "quay.io/biocontainers/mob_suite:1.4.9.1--py_0"`
2. Clone out mob_suite repository and get into the main `mob_suite` folder and get the absolute path stored in `cwd` variable `cwd=$(pwd)`
3. Mount local examples directory and run analyses on the example `SRR3703080_illumina_unicycler.fasta` assembly `docker run --rm -v ${cwd}/mob_suite/example:/mnt/ "quay.io/biocontainers/mob_suite:1.4.9.1--py_0" mob_recon -i /mnt/SRR3703080_illumina_unicycler.fasta -t -o /mnt/SRR3703080
`
4. Check results in the `./mob_suite/example/` folder
5. Modify paths and run mob_recon on your set of files

**Comment by kbessonov1984** [comment]
I've released new docker image running the latest MOB-Suite version. It will be save time for those who do not want to install all dependencies including complex minimus2 AMOS pipeline and ete3 tree rendering library (used by `mob_hostrange` module). 

* To get Docker image run `docker pull kbessonov/mob_suite`
* To convert Docker image into Singularity image run `singularity pull docker://kbessonov/mob_suite:2.0.0`

**Comment by RoxanaZamudio** [comment]
Hi Kirrill,
Thank you so much for your help and advices! For the HPC cluster I chose to use the option: "To convert Docker image into Singularity image run `singularity pull docker://kbessonov/mob_suite:2.0.0`", as you suggested. The `mob_recon` is working very well and I do not have issue.
Thank you again.
Best wishes,
Roxana
