### ISSUE TITLE
galaxy - irida

### ISSUE THREAD

**Issue by happykhan** [phac-nml/mob-suite#26]
Is this going into galaxy  and irida  (as a custom pipeline plugin)?

**Comment by apetkau** [comment]
This should already be in Galaxy (https://toolshed.g2.bx.psu.edu/view/nml/mob_suite/1c5dfecfbb4d). We'll look into adding this to IRIDA.

**Comment by happykhan** [comment]
cool

please mention galaxy on readme,

**Comment by kbessonov1984** [comment]
We are currently working on IRIDA plugin and Galaxy wrapper for MOB-Suite version 2.0 with host range and transfer rate predictions. We are now done with beta testing stage for these new features. We are hoping to update readme as suggested and create better documentation in the following months.

**Comment by jrober84** [comment]
Closing this issue for now, but having an IRIDA wrapper for MOB-suite would definitely be desirable
