### ISSUE TITLE
append() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by jnesme** [phac-nml/mob-suite#27]
Hi,
First, thanks for a practical tool.

I've just reinstalled mobsuite to try the novel feature used to determine host range in a fresh conda environment but I'm now having an error thrown when using mob typer that seems linked to pandas library ?

```
Traceback (most recent call last):
  File "/mibi/users/jnesme/miniconda2/envs/mobsuite_env/bin/mob_typer", line 12, in <module>
    sys.exit(main())
  File "/mibi/users/jnesme/miniconda2/envs/mobsuite_env/lib/python3.6/site-packages/mob_suite/mob_typer.py", line 497, in main
    main_report_mobtyper_df = main_report_mobtyper_df.append(pandas.DataFrame([main_report_data_dict]),sort=False)
TypeError: append() got an unexpected keyword argument 'sort'
```

**Comment by jnesme** [comment]
my bad - posting too fast:
There was a pandas version mix up and a previous install of pandas (0.20) was used instead of the environment specific pandas (0.25)

Now everything is running fine

**Comment by kbessonov1984** [comment]
Hi, Joseph,
Thank you for your nice comments. We are still polishing the host-range module and thank you for letting us know about pandas compatibility issue. I will try to make it version agnostic to avoid issues with deprecated arguments like `sort=F`.
