### ISSUE TITLE
python call :: use sys.executable instead of python

### ISSUE THREAD

**Issue by EricDeveaud** [phac-nml/mob-suite#39]
there is some python call in the mob-suite code written as 
```
p = Popen(['python', ...] )
os.system('python'.... )
```

I suggest you replace verbatim python by sys.executable.
on some situations, users may have a python in their path different form the one scripts have been installed with
NB this is how we perform our installation on our cluster.

this may lead to a call to a different python version, python with different set of modules and so on.

sys.executable will ensure that  you will use the same interpreter,

Eric

**Comment by kbessonov1984** [comment]
Thank you, I've changed code to call python in a more safer way via `sys.executable` in mob_recon on [line 148](https://github.com/phac-nml/mob-suite/blob/327b310699914bb8792aa0fcc4b2dc9292e68cd0/mob_suite/mob_recon.py#L148)
