### ISSUE TITLE
setup.py missing "Programming Language :: Python :: 3.7 "

### ISSUE THREAD

**Issue by tseemann** [phac-nml/mob-suite#40]
Not sure if it is important, but it's not in the 3.7 category.

https://github.com/phac-nml/mob-suite/blob/master/setup.py#L15-L18

**Comment by kbessonov1984** [comment]
Had added Python 3.7 category to the meta data section of the `setup.py`. Do not think it makes any difference, rather assurance that the tool works under Python version 3.7 too. Thank you.
