### ISSUE TITLE
i have a issure regarding setup.py

### ISSUE THREAD

**Issue by sanakousar00** [phac-nml/mob-suite#47]
"""
setup.py: Driving code for MLE function
Authors       : mns
"""
from distutils.core import setup
from Cython.Build import cythonize
import numpy

setup(
    name = "error_function",
    ext_modules = cythonize("/content/drive/My Drive/try/LLSC-CNN/lsc-cnn-master/utils/mle_function/error_function.pyx/", include_path = [numpy.get_include()]),
)

error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-69834224e201> in <module>()
      9 setup(
     10     name = "error_function",
---> 11     ext_modules = cythonize("/content/drive/My Drive/try/LLSC-CNN/lsc-cnn-master/utils/mle_function/error_function.pyx/", include_path = [numpy.get_include()]),
     12 )
     13 

2 frames
/usr/local/lib/python3.6/dist-packages/Cython/Build/Dependencies.py in nonempty(it, error_msg)
    112         yield value
    113     if empty:
--> 114         raise ValueError(error_msg)
    115 
    116 

ValueError: '/content/drive/My Drive/try/LLSC-CNN/lsc-cnn-master/utils/mle_function/error_function.pyx/' doesn't match any files

**Comment by jrober84** [comment]
It is recommended that you install the MOB-suite through conda. Could you try creating a fresh conda environment and installing the MOB-suite?

**Comment by jrober84** [comment]
I am closing this issue for now due to inactivity but please feel free to reopen it if your problem persists
