### ISSUE TITLE
using own mob_cluster db error 

### ISSUE THREAD

**Issue by Lneffe** [phac-nml/mob-suite#53]
Hello!
I generated a mob_cluster database of closed plasmids of two clinical E. coli strains using the mob_cluster function. During this process I did not encouter any errors.
When I wanted to check if this database works with some of the assemblies that I used to generate it, I encoutered the following error: 

`
Traceback (most recent call last):
  File "/home/lneffe/miniconda3/envs/mob-suite/bin/mob_recon", line 8, in <module>
    sys.exit(main())
  File "/home/lneffe/miniconda3/envs/mob-suite/lib/python3.6/site-packages/mob_suite/mob_recon.py", line 580, in main
    (pcl_clusters,reference_sequence_hits,contig_hit_scores) = contig_blast_group(filtered_blast, min_overlapp)
ValueError: not enough values to unpack (expected 3, got 0)
`

What could be the reason for this? 

Best wishes,
Lisa

**Comment by kbessonov1984** [comment]
Hi Lisa,
Sorry to hear about another issue. Could you send us mock versions of the fasta and taxonomy files used to create/update a new plasmid database? You can take an existing public plasmid sequence and document all your steps from database creation until `mob_recon` run. I would like to test it on our end too to gain more clarity. Looks like something is missing in metadata. You can drag and drop files into comments section. I've also assigned this issue to the developer of the `mob_cluster` module who will be available to look at it next week.

**Comment by Lneffe** [comment]
Hi Kirill,
not sure what you mean by taxonomy file. I didn´t use something like that for creating the mob_cluster. 
Maybe that is the problem. 
I used:
`mob_cluster --mode build --infile myfastafile --outdir myfolder` 
Then I added the plasmids of the 2nd strain
`mob_cluster --mode update --infile multifastafile2 --outdir folder -c clusters.txt -r references_updated.fasta`

I will generate the script and send it to you.

Thanks,
Lisa

**Comment by Lneffe** [comment]
Hi! 
just wanted to check if my example is reproducible for you?
If I can do anything else or provide further information, please let me know. 

Looking forward to your response,
Lisa

**Comment by kbessonov1984** [comment]
Hi Lise,
My apologies for the long wait. I am now on a leave and main developer is also away. 
I was able to resolve the issue running mob-suite version `2.0.5`. Eventually I do recommend to update to current most recent version `3.0.0`
[testrun-native_eco_bs_00020.zip](https://github.com/phac-nml/mob-suite/files/4736850/testrun-native_eco_bs_00020.zip)
 as it has major improvements in speed and reproducibility with alphanumerical cluster codes.

Below are the results from your data (many thanks as it makes testing much easier on our end).

1) Concat all plasmid files instead of build and update database steps
```
cat native_eco_bs_000* > new_plasmids.fasta
```
2)Run mob_cluster to generate all required files including `cluster.txt` (with contig cluster codes), updated plasmid database file `references_updated.fasta` with modified FASTA headers with appended plasmid cluster code. Do not use `new_plasmids.fasta` as its headers do not have cluster codes which caused an error. The `-o .` means that I want to output files in my current directory instead of a folder.
```
mob_cluster -m build -i new_plasmids.fasta -o .
```

3) Create an updated plasmid database MASH sketch from the `references_updated.fasta` file. Importantly use the `-i` parameter. This is a key step as again we need a FASTA file with correct headers such as `>eco_bs_10_2_length=111145_depth=0.43x_circular=true|13` where cluster codes are delimited by the `|` symbol
```
mash sketch -i  references_updated.fasta
```

4)Lastly run `mob_recon` or `mob_typer` specifying new plasmid database and corresponding MASH sketch. I used one of your input sequences for illustration purposes.
```
mob_recon -i native_eco_bs_00020_assembly_plasmids.fasta -o testrun-native_eco_bs_00020  --plasmid_db references_updated.fasta  --plasmid_mash_db references_updated.fasta.msh
```

I've attached results from the step #4 command. There were a total of 7 plasmids.

Best wishes and thank you for letting

**Comment by Lneffe** [comment]
Hello Kirill,
thank you for your help. I followed your steps and it all worked untill the part (4.) when I observed the same error as before. 

`2020-06-06 14:36:59,777 mob_suite.mob_recon INFO: Running contig blast on references_updated.fasta [in /home/lneffe/miniconda3/envs/mob-suite/lib/python3.6/site-pac                               kages/mob_suite/mob_recon.py:576]
Traceback (most recent call last):
  File "/home/lneffe/miniconda3/envs/mob-suite/bin/mob_recon", line 8, in <module>
    sys.exit(main())
  File "/home/lneffe/miniconda3/envs/mob-suite/lib/python3.6/site-packages/mob_suite/mob_recon.py", line 580, in main
    (pcl_clusters,reference_sequence_hits,contig_hit_scores) = contig_blast_group(filtered_blast, min_overlapp)
ValueError: not enough values to unpack (expected 3, got 0)
`

As you mentioned I then tried to use the mob_suite version 3.0.
I was not able to install it via conda under python 3.7, but only when using the lower version
Python 3.6.10 :: Anaconda, Inc.
I tried to use the mob_cluster tool, despite the low python version but I encoutered the following error: 


`Traceback (most recent call last):
  File "/home/lneffe/miniconda3/envs/mob-suite3/bin/mob_cluster", line 10, in <module>
    sys.exit(main())
  File "/home/lneffe/miniconda3/envs/mob-suite3/lib/python3.6/site-packages/mob_suite/mob_cluster.py", line 516, in main
    record_identifications = read_file_to_dict(taxonomy_file, ['sample_id', 'organism'], separater="\t")
  File "/home/lneffe/miniconda3/envs/mob-suite3/lib/python3.6/site-packages/mob_suite/utils.py", line 465, in read_file_to_dict
    data = pd.read_csv(file, sep=separater, header=0, names=header, encoding="UTF-8")
  File "/home/lneffe/miniconda3/envs/mob-suite3/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lneffe/miniconda3/envs/mob-suite3/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/home/lneffe/miniconda3/envs/mob-suite3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/home/lneffe/miniconda3/envs/mob-suite3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 952, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1013, in pandas._libs.parsers.TextReader._convert_column_data
pandas.errors.ParserError: Too many columns specified: expected 2 and found 1
`
The Mob_typer tool version 3.0 worked on the concatenated fasta file. 
But the issue is again with mob_cluster. 
Could you show an example of the required taxonomy file? 
What are the recommended python and conda versions for mob_suite 3.0?

Many thanks in advance,
Lisa

**Comment by Lneffe** [comment]
Hi Kirill,
sorry for producing so many posts here! 
I had a look on the output you provided and found that there are only 7 out of 8 plasmids found. 
We were pretty sure that the strain eco_bs_00020 has 8 plasmids, but mob_recon designated on of them as chromsomal, although this contig is even part of the database and should therefore be recognized to my understanding.
What is the reason for this classification? Should this be masked with --g option?

Best wishes,
Lisa

**Comment by jrober84** [comment]
Hey @Lneffe ,

No problem at all, there was actually an issue with the conda recipe having old dependencies that blocked installation through conda and Kirill has resolved those now. I have done some testing with your data in MOB-suite v. 3.0.0 and when you generate a new database and supply it to MOB-recon it correctly uses the new database to identify your plasmids. The process is overhauled to make it faster and more streamlined to add sequences to existing databases.

#Create new conda environment
conda create -n mobsuite3 python==3.7 
- You can use any version >= 3.7
conda activate mobsuite3

#install mobsuite
conda install -y mob_suite

#Initialize the databases
mob_init

#Run MOB-typer on your set of plasmids
cat native_eco_bs_00020_assembly_plasmids.fasta native_eco_bs_00010_assembly_plasmids.fasta > merged.fasta

mob_typer -i merged.fasta -o mobtyper_results.txt --multi

#Run MOB-cluster on your merged set of plasmids
-Prepare a taxonomy.txt file using your sample_ids and list the organism in a tab-separated file with the following headers 1)sample_id 2) organism. The sample_id must match your fast file identifiers exactly. If you don't know the host, you can use unknown or bacteria as an identification.

-These step will build a mob_recon database that is ONLY your plasmids. If you want to add your plasmids to the result of the already existing plasmids then you would use mob-cluster in update mode.


mob_cluster -m build -i merged.fasta -o mobcluster -t taxonomy.txt

--This will produce a database where your plasmids have been ADDED to an existing one
mob_cluster --mode update -f new_plasmids.fasta -p mobtyper_report.txt -t taxonomy.txt --outdir mobcluster_update -c ~/path/to/default/mob_suite/database/clusters.txt -r /path/to/default/mob_suite/database/ncbi_plasmid_full_seqs.


 #prepare a MOB-recon database directory
- The easiest way to produce a db directory is to copy the existing db folder for mob-recon
which mob_recon
find "/conda/env/path" -name "database"
cp ~/path/mob_recon/database .

- copy clusters.txt from your mobcluster run into your ./database/
cp mobcluster/clusters.txt database/
cp mobcluster/references_updated.fasta database/ncbi_plasmid_full_seqs.fas
makeblastdb -in database/ncbi_plasmid_full_seqs.fas -dbtype nucl
mash sketch -i database/ncbi_plasmid_full_seqs.fas

**Comment by Lneffe** [comment]
Hi @jrober84!
Thank you! I am now running the updated tool in the environment as you suggested.

Unfortunately it is still not working to use the database for me. 
I followed your steps, but when it comes to using mob-recon it stops. 

How do you exactly specifiy the path to the newly created db, when starting mob:recon?

I am using: 
`mob_recon -i path/to/assembly -o path/to/my/outdir  --plasmid_db /path/to/newfolder/with/my/owndb/20200623_testing_10_14_20/databases/ --plasmid_mash_db /vol/projects/MOBA/eco_bs_clin_iso/plasmid_typing_annotation/20200623_testing_10_14_20/databases/ncbi_plasmid_full_seqs.fas.msh --run_overhang -t --force`

but I still get an error and no output:
`2020-06-24 11:51:38,999 root INFO: Assigning contigs to plasmid groups [in /home/lneffe/miniconda3/envs/mobsuite3/lib/python3.7/site-packages/mob_suite/mob_recon.py:1191]
Traceback (most recent call last):
  File "/home/lneffe/miniconda3/envs/mobsuite3/bin/mob_recon", line 10, in <module>
    sys.exit(main())
  File "/home/lneffe/miniconda3/envs/mobsuite3/lib/python3.7/site-packages/mob_suite/mob_recon.py", line 1234, in main
    data['mash_neighbor_identification'] = reference_sequence_meta[top_ref_id]['organism']
KeyError: 'eco_bs_10_4_length=6647_depth=7.49x_circular=true'
`
I am afraid there is something wrong with the names I am using for my plasmids?
To they have to keep the ">" in the fasta header?
I deleted this in the ID file, because it was removed in the mob_typer report as well. 

Best wishes,
Lisa

**Comment by jrober84** [comment]
you use the mob_recon -d /path/to/db flag to specify a db folder. which would be setup as I described above and the program would handle identifying each of the needed components.  Try that and see what happens

**Comment by Lneffe** [comment]
Great, it works!

Thanks a lot,
Lisa
