### ISSUE TITLE
Error when installing from Conda

### ISSUE THREAD

**Issue by jpaganini** [phac-nml/mob-suite#70]
Hi guys,

How are you? I hope you are doing fine.
Thanks a lot for this wonderful tool, I'm using it a lot in my research!
I wanted to report an issue when installing from Conda (see below). Any idea why this might happen?

----------------------------------------------------------------------------------------------------------------------------------------
Input

`(mob-suite_mmbioit) [jpaganini@hpcs03 envs]$ conda install -c bioconda mob_suite`

------------------------------------------------------------------------------------------------------------------------------------------
Output

Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/dla_mm/jpaganini/data/miniconda3/envs/mob-suite_mmbioit

  added / updated specs:
    - mob_suite

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    biopython-1.78             |   py38h7b6447c_0         2.1 MB
    blosc-1.20.0               |       hd408876_0          71 KB
    boost-1.73.0               |          py38_11          25 KB
    ete3-3.1.2                 |     pyh9f0ad1d_0         1.8 MB  conda-forge
    libboost-1.73.0            |      h37e3b65_11        13.9 MB
    mkl_fft-1.2.0              |   py38h23d657b_0         157 KB
    numpy-1.19.1               |   py38hbc911f0_0          21 KB
    numpy-base-1.19.1          |   py38hfa32c7d_0         4.2 MB
    pandas-1.1.2               |   py38he6710b0_0         8.5 MB
    pip-20.2.3                 |           py38_0         1.7 MB
    py-boost-1.73.0            |  py38h962f231_11         219 KB
    python-3.8.5               |       h7579374_1        49.3 MB
    scipy-1.5.2                |   py38h0b6359f_0        14.5 MB
    setuptools-50.3.0          |           py38_0         729 KB
    snappy-1.1.8               |       he6710b0_0          40 KB
    xorg-libx11-1.6.12         |       h516909a_0         917 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        98.1 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  biopython          pkgs/main/linux-64::biopython-1.78-py38h7b6447c_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  blast              bioconda/linux-64::blast-2.5.0-hc0b0e79_3
  blosc              pkgs/main/linux-64::blosc-1.20.0-hd408876_0
  boost              pkgs/main/linux-64::boost-1.73.0-py38_11
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.7.22-0
  certifi            pkgs/main/linux-64::certifi-2020.6.20-py38_0
  dbus               pkgs/main/linux-64::dbus-1.13.16-hb2f20db_0
  ete3               conda-forge/noarch::ete3-3.1.2-pyh9f0ad1d_0
  expat              pkgs/main/linux-64::expat-2.2.9-he6710b0_2
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-he4413a7_1000
  freetype           pkgs/main/linux-64::freetype-2.10.2-h5ab3b9f_0
  glib               pkgs/main/linux-64::glib-2.65.0-h3eb4bd4_0
  gst-plugins-base   pkgs/main/linux-64::gst-plugins-base-1.14.0-hbbd80ab_1
  gstreamer          pkgs/main/linux-64::gstreamer-1.14.0-hb31296c_0
  hdf5               pkgs/main/linux-64::hdf5-1.10.4-hb1b8bf9_0
  icu                pkgs/main/linux-64::icu-58.2-he6710b0_3
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.2-254
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  krb5               pkgs/main/linux-64::krb5-1.18.2-h173b8e3_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libboost           pkgs/main/linux-64::libboost-1.73.0-h37e3b65_11
  libcurl            pkgs/main/linux-64::libcurl-7.71.1-h20c2e04_1
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc             pkgs/main/linux-64::libgcc-7.2.0-h69d50b8_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libssh2            pkgs/main/linux-64::libssh2-1.9.0-h1ba5d50_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             pkgs/main/linux-64::libxcb-1.14-h7b6447c_0
  libxml2            pkgs/main/linux-64::libxml2-2.9.10-he19cac6_1
  libxslt            pkgs/main/linux-64::libxslt-1.1.34-hc22bd24_0
  lxml               pkgs/main/linux-64::lxml-4.5.2-py38hefd8a0e_0
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.2-he6710b0_1
  lzo                pkgs/main/linux-64::lzo-2.10-h7b6447c_2
  mash               bioconda/linux-64::mash-1.1-0
  mkl                pkgs/main/linux-64::mkl-2020.2-256
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py38he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.2.0-py38h23d657b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.1-py38h0573a6f_0
  mob_suite          bioconda/noarch::mob_suite-3.0.0-py_1
  mock               pkgs/main/noarch::mock-4.0.2-py_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  numexpr            pkgs/main/linux-64::numexpr-2.7.1-py38h423224d_0
  numpy              pkgs/main/linux-64::numpy-1.19.1-py38hbc911f0_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.19.1-py38hfa32c7d_0
  openssl            pkgs/main/linux-64::openssl-1.1.1h-h7b6447c_0
  pandas             pkgs/main/linux-64::pandas-1.1.2-py38he6710b0_0
  pcre               pkgs/main/linux-64::pcre-8.44-he6710b0_0
  pip                pkgs/main/linux-64::pip-20.2.3-py38_0
  py-boost           pkgs/main/linux-64::py-boost-1.73.0-py38h962f231_11
  pycurl             pkgs/main/linux-64::pycurl-7.43.0.5-py38h1ba5d50_0
  pyqt               pkgs/main/linux-64::pyqt-5.9.2-py38h05f1152_4
  pytables           pkgs/main/linux-64::pytables-3.6.1-py38h9fd0a39_0
  python             pkgs/main/linux-64::python-3.8.5-h7579374_1
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pytz               pkgs/main/noarch::pytz-2020.1-py_0
  qt                 pkgs/main/linux-64::qt-5.9.7-h5867ecd_1
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  scipy              pkgs/main/linux-64::scipy-1.5.2-py38h0b6359f_0
  setuptools         pkgs/main/linux-64::setuptools-50.3.0-py38_0
  sip                pkgs/main/linux-64::sip-4.19.13-py38he6710b0_0
  six                pkgs/main/noarch::six-1.15.0-py_0
  snappy             pkgs/main/linux-64::snappy-1.1.8-he6710b0_0
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.35.1-py_0
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.12-h516909a_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
  zstd               pkgs/main/linux-64::zstd-1.4.5-h9ceee32_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
numpy-base-1.19.1    | 4.2 MB    | ################################################################################################################################################################# | 100% 
xorg-libx11-1.6.12   | 917 KB    | ################################################################################################################################################################# | 100% 
setuptools-50.3.0    | 729 KB    | ################################################################################################################################################################# | 100% 
py-boost-1.73.0      | 219 KB    | ################################################################################################################################################################# | 100% 
boost-1.73.0         | 25 KB     | ################################################################################################################################################################# | 100% 
libboost-1.73.0      | 13.9 MB   | ################################################################################################################################################################# | 100% 
pip-20.2.3           | 1.7 MB    | ################################################################################################################################################################# | 100% 
mkl_fft-1.2.0        | 157 KB    | ################################################################################################################################################################# | 100% 
python-3.8.5         | 49.3 MB   | ################################################################################################################################################################# | 100% 
pandas-1.1.2         | 8.5 MB    | ################################################################################################################################################################# | 100% 
numpy-1.19.1         | 21 KB     | ################################################################################################################################################################# | 100% 
blosc-1.20.0         | 71 KB     | ################################################################################################################################################################# | 100% 
scipy-1.5.2          | 14.5 MB   | ################################################################################################################################################################# | 100% 
snappy-1.1.8         | 40 KB     | ################################################################################################################################################################# | 100% 
biopython-1.78       | 2.1 MB    | ################################################################################################################################################################# | 100% 
ete3-3.1.2           | 1.8 MB    | ################################################################################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::mob_suite-3.0.0-py_1'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::mob_suite-3.0.0-py_1
location of failed script: /home/dla_mm/jpaganini/data/miniconda3/envs/mob-suite_mmbioit/bin/.mob_suite-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/dla_mm/jpaganini/data/miniconda3/envs/mob-suite_mmbioit/bin/mob_init", line 7, in <module>
    from mob_suite.mob_init import main
  File "/home/dla_mm/jpaganini/data/miniconda3/envs/mob-suite_mmbioit/lib/python3.8/site-packages/mob_suite/mob_init.py", line 8, in <module>
    from mob_suite.blast import BlastRunner
  File "/home/dla_mm/jpaganini/data/miniconda3/envs/mob-suite_mmbioit/lib/python3.8/site-packages/mob_suite/blast/__init__.py", line 9, in <module>
    from pandas.io.common import EmptyDataError
ImportError: cannot import name 'EmptyDataError' from 'pandas.io.common' (/home/dla_mm/jpaganini/data/miniconda3/envs/mob-suite_mmbioit/lib/python3.8/site-packages/pandas/io/common.py)

return code: 1

()

**Comment by jrober84** [comment]
Thank you for your kind words. This issue is related to a pandas version issue, newer versions of pandas don't have EmptyData error. We have removed this dependency in a minor update 3.0.1 which will be released soon. However, a workaround in the meantime is to use an older version of pandas. conda install -y mob_suite==3.0.0 pandas==1.0.5. This is the same issue as #63

**Comment by jpaganini** [comment]
Thanks a lot for your prompt reply! I tried the work around that you suggsted and it worked perfect! Thanks for the help!
