### ISSUE TITLE
Mash Dists wihtin and between clusters

### ISSUE THREAD

**Issue by Lneffe** [phac-nml/mob-suite#71]
Hello! 
With your tool mob_cluster I combined 372 closed plasmids of 97 E. coli strains into 81 primary clusters. For now, I used the primary clustering step only because the secondary clustering algorithm to simplify my dataset as much as possible. 
My question now is how can I determine the distance between the clusters (to see which are more or less similar from each other) and within a cluster (I know the maximum mash distance within a cluster should be 0,06 in mobsuite 3.0?)?
Is there any value in the mobsuite output that would already answer question?
If not do you happen to have a recommendation for an additional tool?

Many thanks in advance,
Lisa

**Comment by jrober84** [comment]
Hello,

This is related to #50 . Within the MOB-suite doesn't have the intervening levels of similarity which would provide you the information you're looking for. You could use MOB-cluster on your dataset and change the levels of partitions to cover the levels of diversity you want to cover.  However, this depends a lot on what kind of plasmids you are looking for and what questions you are looking to address. If you are looking at very similar plasmids within a cluster and want to get a sense of their "core-gene" phylogeny then using something like roary to find the core genes and then feed that into a tree building algorithm.  If you are looking at divergent plasmids and want to get a sense of which genes are shared between clusters, roary can also be helpful in that regard.  Hopefully that helps.
