### ISSUE TITLE
guidance for downloading the database

### ISSUE THREAD

**Issue by happykhan** [phac-nml/mob-suite#74]
hi all, 

im stuck on the mob_init step. where i cant seem to download the databases through the mob_init. 
I can download the files else where and get them on this machine, but then how do i get mob_init to use those download files. 

Everytime it seems to want to download the files again.

**Comment by jrober84** [comment]
mob_init isn't designed to take a predownloaded set of files, I will add this as an enhancement to the software to allow for users to supply predownloaded files with the tool.

**Comment by kbessonov1984** [comment]
@happykhan The `mob_init` is only required to be run if database files are not available. If they are, there is no need to run `mob_init`. At this point the MOB-Suite tools should recognize presence of the initialized database and not run `mob_init`. By copying initialized `databases` folder to other MOB-Suite install should initialize the new MOB-Suite install which could be useful if a particular machine has no internet connection.

In addition, latest conda recipe the `mob_init` is run during package install via the `post-link.sh` [script](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mob_suite)

**Comment by jrober84** [comment]
This seems to be resolved
