### ISSUE TITLE
Error on ETE3 

### ISSUE THREAD

**Issue by happykhan** [phac-nml/mob-suite#76]
Hi . 

I keep running into this issue with 

`2020-11-25 10:50:34,556 root ERROR: Exiting due to lock file not removed: /mob-suite/venv/lib/python3.7/site-packages/mob_suite-3.0.0-py3.7.egg/mob_suite/databases/ETE3_DB.lock [in /mob-suite/venv/lib/python3.7/site-packages/mob_suite-3.0.0-py3.7.egg/mob_suite/mob_recon.py:1007]`
`

not sure how to proceed. I am trying to use a database  directory from else where, maybe its looking in its default location?

mob_recon -o mob_bc01 -i plas_bc01_3.fasta  -d data/ -f

**Comment by happykhan** [comment]
Yeah. I rerun with mob_init being able to install the database where it wants. 

and then ran mob_recon -o mob_bc01 -i plas_bc01_3.fasta  -f [not specifying the db]

and it went through fine.

**Comment by jrober84** [comment]
OK great, I will close this for now but if the issue occurs again please re-open
