### ISSUE TITLE
is pyqt still a required dependency ? 

### ISSUE THREAD

**Issue by EricDeveaud** [phac-nml/mob-suite#78]
Hello, 

while building mob-suite/3.0.1 one can see PyQT5 as a dependency. 
is this one still required 

none of the python files from mob-suite import pyqt ?
as far as I understand pyqt was needed for TreeStyle that was removed on version 2.0.1
please ket me know 

PS mob-suite/3.0.1 run smoothly after pyqt renmoveal in my basic tests
and after removing pyqt from `EGG-INFO/requires.txt`

regards

Eric

**Comment by kbessonov1984** [comment]
Hi Eric,
Indeed,  `pyqt` is not required  anymore and was removed in conda recipe, but the library needs to be removed from the `setup.py`. Thank you for spotting it.  The `pyqt` was previously required in previous MOB-Suite versions to render the taxonomy tree for the host range module.

**Comment by jrober84** [comment]
The pyqt dependancy has been removed from the pending release of MOB-suite v. 3.1.0
