### ISSUE TITLE
-s option does not change output file names

### ISSUE THREAD

**Issue by hkaspersen** [phac-nml/mob-suite#79]
Hello, and thank you for a brilliant tool!
I just updated to the newest version, and tested mob_recon with the -s option. This option fits nicely into the pipeline I am creating, as it makes the output more traceable with sample IDs. 
However, when I ran it, no change was seen in the output files; they have the same names regardless of the -s option.
This is the command I used:
`mob_recon -i ../2016-02-723_assembly.fasta -o test -f -u -t --debug -s 2016-02-723`
This was then the output:
```
chromosome.fasta   mobtyper_results.txt  plasmid_AA378.fasta  plasmid_AA673.fasta  plasmid_AC509.fasta
contig_report.txt  plasmid_AA179.fasta   plasmid_AA579.fasta  plasmid_AB042.fasta
```
I also tried with `-s test` to see if that made any difference, but the output was the same.
I would very much appreciate your help with this!

**Comment by jrober84** [comment]
Hello, 

Glad to hear that the tool is useful for your application. The -s option is meant to change the sample_id field in each of the reported files produced by the MOB-suite. Previously, it would populate this based on the file names that were run and this option was added to give user control over that. The output file structure was not intended to be changed by this option. For your application, are you saying having an output file prefix flag would be useful?

**Comment by hkaspersen** [comment]
I see. A flag to control the prefix of the output files would be very useful!

**Comment by jrober84** [comment]
I have marked this as an enhancement for future releases

**Comment by jrober84** [comment]
The latest release v 3.1.0 will include this ability
