### ISSUE TITLE
output result files to running directory

### ISSUE THREAD

**Issue by hkaspersen** [phac-nml/mob-suite#80]
I was wondering if it was possible to output result files to the running directory? Currently the `-o .` does not work and give me the following error message:
`OSError: [Errno 22] Invalid argument: '.'`

Just a suggestion, it would be nice to have the option to do this!

**Comment by jrober84** [comment]
You can output  to the working directory by using './' .

**Comment by hkaspersen** [comment]
Hello again an thanks for a swift reply!
Unfortunately I get the same error with the `./` as I do with `.` alone. Using `.` works with other programs though, so shouldn't be a system issue (I am running this on an HPC cluster).
