### ISSUE TITLE
Question Regarding Mob-recon

### ISSUE THREAD

**Issue by YasirKusay** [phac-nml/mob-suite#83]
(Sorry if this is not the correct place to post this). While looking for suitable tools for my work, I found this to be relevant to what I need. With regards to Mob-recon, are the contigs in chromosome.fasta in the correct order?

**Comment by kbessonov1984** [comment]
Hi Yasir,
No problem. We also have contact emails that you can use for questions (james.robertson@canada.ca and kyrylo.bessonov@canada.ca) 

Could you please specify if by the "correct order" you mean the same order as in the input fasta file? Why order is relevant in your context?

**Comment by YasirKusay** [comment]
Hi @kbessonov1984, by correct order, I mean that the chromosome is assembled, piecing together the contigs in the correct order.

**Comment by jrober84** [comment]
MOB-suite doesn't perform any scaffolding so the order is just by contig id number.  If you want to order contigs then you could consider a tool like https://github.com/fenderglass/Ragout. Assembly is a completely different process and there are many excellent assemblers available. SPAdes, Unicycler etc. So we will not be building assembly into the MOB-suite
