### ISSUE TITLE
ERROR: Something went wrong with database download or unpackingCheck MOB-Suite databases directory and your Internet connection

### ISSUE THREAD

**Issue by danielapfh** [phac-nml/mob-suite#86]
Hello everybody

To the creators, thank you very much for developing the mob-suite and making it public. When installing mob_suire 3.0.0 I get some errors and I really don't know how to solve them. Could anyone give me some advice on how to fix it?
Thank you very much in advance.

This is the error:
   mob_suite.mob_recon INFO: MOB-recon version 3.0.0 [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3.7 .egg / mob_suite / mob_recon.py: 983]
  mob_suite.mob_recon INFO: SUCCESS: Found program blastn at / home / Estudiantesgenetica / miniconda2 / bin / blastn [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/ mob_suite-3.0.1-py3.7.egg / mob_suite / utils.py: 571]
  mob_suite.mob_recon INFO: SUCCESS: Found program makeblastdb at / home / Estudiantesgenetica / miniconda2 / bin / makeblastdb [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/ mob_suite-3.0.1-py3.7.egg / mob_suite / utils.py: 571]
  mob_suite.mob_recon INFO: SUCCESS: Found program tblastn at / home / Estudiantesgenetica / miniconda2 / bin / tblastn [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/ mob_suite-3.0.1-py3.7.egg / mob_suite / utils.py: 571]
   mob_suite.mob_recon INFO: Processing fasta file 33Kpn12-PKPC.fasta [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3. 7.egg / mob_suite / mob_recon.py: 1004]
  mob_suite.mob_recon INFO: Analysis directory my_out_dir [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3.7.egg/mob_suite /mob_recon.py:1005]
  mob_suite.mob_recon INFO: MOB-databases need to be initialized, this will take some time [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0 .1-py3.7.egg / mob_suite / utils.py: 645]
  mob_suite.mob_recon INFO: Return code 1 [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3.7.egg/mob_suite /utils.py:653]
  **mob_suite.mob_recon ERROR: Something went wrong with database download or unpackingCheck MOB-Suite databases directory and your Internet connection. [in /home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3.7.egg/mob_suite/utils.py:657]**

The program starts normally, but in the end it gives me an error with the databases. I already executed the mob_init command several times and also downloaded the databases manually as indicated on the page. I would greatly appreciate your help, I have already downloaded everything several times and it still does not work. 

Postscript: I already confirmed my internet connection several times and I don't think it's the problem either

**Comment by kbessonov1984** [comment]
@danielapfh Hola Daniel! Certainly we can help with the install issue. The initialization procedure is quite intense and it is hard to tell what exactly went wrong. My hypothesis is that either unzip libraries are not installed or `ete3` library taxonomy database failed to be initialized. All we know that the init function failed with exit code 1.
Please provide more details on what is your setup and how are you installing MOB-Suite (from source, as a conda package, as a PyPI package). There is also an option to run MOB-Suite as a Singularity container without any installation pains.
Meanwhile you can try a couple of this suggestion in your troubleshooting.
1) Run `mob_init` again and post error messages here
2) Manually initialize database in `/home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3.7.egg/mob_suite/databases` folder. For that download a) download database zip file from the mirror(s) and unzip it in the `Data` folder; b) make BLAST database from the repetitive elements (`repetitive.dna.fas`) and plasmid database (`ncbi_plasmid_full_seqs.fas`) fasta files, generate MASH sketch from `ncbi_plasmid_full_seqs.fas` plasmid database fasta file (refer to lines 203-216: https://github.com/phac-nml/mob-suite/blob/master/mob_suite/mob_init.py); c)initialize ete3 taxonomy database by running:
    ```bash
    python -c "import os; from ete3 import NCBITaxa; database_directory='/home/estudiantesgenetica/miniconda2/lib/python3.7/site-packages/mob_suite-3.0.1-py3.7.egg/mob_suite/databases'; ete3taxadbpath = os.path.abspath(os.path.join(database_directory,'taxa.sqlite')); ncbi = NCBITaxa(); ncbi.dbfile=ete3taxadbpath; ncbi.update_taxonomy_database();"
    ```
    You should see `taxa.sqlite` and `taxa.sqlite.traverse.pkl` files;  d) if all these steps went well then you can generate empty `status.txt` file in the `Data` directory by running `touch status.txt` which would signal successful database init.

Another simpler option is to run Singularity container with instructions described [here](https://biocontainers.pro/tools/mob_suite). The image will be downloaded to you `.cache` directory and `mob_suite` will be run locally on subsequent calls. Also `conda` is nice alternative where database init is done at conda package install.
