### ISSUE TITLE
Help with interpreting results

### ISSUE THREAD

**Issue by tseemann** [phac-nml/mob-suite#9]
I ran on _E.faecium_ with 3 plasmids, that are in Refseq.

```
LOCUS       NC_017022            2955294 bp    DNA     circular CON 23-MAR-2017
LOCUS       NC_017032              56520 bp    DNA     circular CON 23-MAR-2017
LOCUS       NC_017023               3847 bp    DNA     circular CON 23-MAR-2017
LOCUS       NC_017024               4119 bp    DNA     circular CON 23-MAR-2017

1   file_id                     0085.gbk.fasta
2   num_contigs                 4
3   total_length                3019780
4   gc                          38.30749259879859
5   rep_type(s)                 rep_cluster_1742,rep_cluster_1077,rep_cluster_935,rep_cluster_889
6   rep_type_accession(s)       001162__CP011831_00015,000325__NC_017023_00001,002420__CP003354_00001,002369__NC_021995_00001
7   relaxase_type(s)            MOBP,MOBV,MOBV,MOBP
8   relaxase_type_accession(s)  NC_019240_00008,NC_017023_00004,NC_017024_00005,NC_021995_00038
9   mpf_type                    MPF_T
10  mpf_type_accession(s)       NC_011642_00014,NC_020208_00096
11  orit_type(s)                -
12  orit_accession(s)           -
13  PredictedMobility           Conjugative
14  mash_nearest_neighbor       CP003352
15  mash_neighbor_distance      0.151946
16  mash_neighbor_cluster       1642
```

I am not sure how to interpret the results.

How do i know which contigs it found things on?
How to interconnect the comma separated rows?
Is there only ever 2 lines of output? If so, can you transpose the results?

**Comment by jrober84** [comment]
mob_typer assumes that all contigs in a file belong to a single plasmid and so in this case, it is presenting the summary results for a mega plasmid containing all of these contigs. mob_recon does the work of identifying the plasmid contigs when using assemblies with chromosomes and one or more plasmids. mob_recon --infile input_assembly.fasta --outdir outfir --run_typer will run the plasmid detection stages and separate out the individual plasmids. Those results will then run through mob_typer and you will get a breakdown report for each plasmid.  The aggregated mob_typer report will have as many lines as there are plasmids with a header row.
