### ISSUE TITLE
param defaults in script docs

### ISSUE THREAD

**Issue by nick-youngblut** [phac-nml/mob-suite#91]
It would help to have the parameter defaults in the script docs. Example code to automatically add defaults:

```
class CustomFormatter(argparse.ArgumentDefaultsHelpFormatter,
                      argparse.RawDescriptionHelpFormatter):
    pass

parser = argparse.ArgumentParser(description=desc, epilog=epi,
                                 formatter_class=CustomFormatter)
```

**Comment by jrober84** [comment]
Thank you very much for this!  This will definitely make things easier for users. I have implemented these changes and they will be in the next version 3.1.0
