### ISSUE TITLE
mob_typer: --analysis_dir

### ISSUE THREAD

**Issue by nick-youngblut** [phac-nml/mob-suite#92]
Based on the script docs, it's not clear what `--analysis_dir` denotes. The script doc param help just states `'Analysis directory'`, and there's nothing in the README that I can find about it. I'm guessing that the 'Analysis directory' is the designated working directory for the script, but it's not clear without experimentation or assessment of the code.

**Comment by jrober84** [comment]
Thank you for pointing that out, I have updated the documentation to reflect it is a working directory for temporary results. The next version 3.1.0 will reflect this.
