### ISSUE TITLE
conda installation error

### ISSUE THREAD

**Issue by Anto007** [phac-nml/mob-suite#94]
Hi, 

I found the below error when attempting installation via conda. The error doesn't go away even when I include mob_suite==3.0.0 and pandas==1.0.5 in my .yml file. Any help here would be appreciated. My .yml file looks like the below
name: null

channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - numpy=1.16.5
  - pandas=1.0.5
  - mob_suite=3.0.0

Below are the command-line and error messages I got.
`conda env create --prefix ./conda_mob_suite_env --file mob_suite_environment.yml`
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'bioconda::mob_suite-3.0.3-pyhdfd78af_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::mob_suite-3.0.3-pyhdfd78af_0
location of failed script: /home/tools/conda_mob_suite_env/bin/.mob_suite-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/tools/conda_mob_suite_env/bin/mob_init", line 7, in <module>
    from mob_suite.mob_init import main
  File "/home/tools/conda_mob_suite_env/lib/python3.8/site-packages/mob_suite/mob_init.py", line 8, in <module>
    from mob_suite.blast import BlastRunner
  File "/home/tools/conda_mob_suite_env/lib/python3.8/site-packages/mob_suite/blast/__init__.py", line 8, in <module>
    import pandas as pd
  File "/home//.local/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
  File "/home/.local/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: this version of pandas is incompatible with numpy < 1.16.5
your numpy version is 1.16.4.
Please upgrade numpy to >= 1.16.5 to use this pandas version
return code: 1

()

**Comment by kbessonov1984** [comment]
Glad to hear it work the other way. It seems you had an old numpy library installed in the Conda environment that caused this pandas and numpy issue:

`ImportError:this version of pandas is incompatible with numpy < 1.16.5
your numpy version is 1.16.4.
Please upgrade numpy to >= 1.16.5 to use this pandas version
`

Will update Conda recipe to explicitly ask for numpy 1.16.5 and above
