### ISSUE TITLE
can't download the database

### ISSUE THREAD

**Issue by shaodongyan** [phac-nml/mob-suite#95]
Sorry,But i can't open the database's website https://share.corefacility.ca/index.php/s/GJOgxxtbhWoX8fV/download.

**Comment by jrober84** [comment]
Sorry for the delay, that mirror went down and we have switched over to a new one and the current MOB-suite uses that DB

**Comment by aldertzomer** [comment]
Just installed it from conda and the link to corefacility is still there. Had to comment it out in config.json
