### ISSUE TITLE
Slow running

### ISSUE THREAD

**Issue by zhichusun** [phac-nml/mob-suite#96]
When I run a large amount of data, the program runs very slowly, and the number of threads does not change. What should I do? Can anyone help me? Thank you very much.code show as below
mob_typer --multi --infile /root/ranseti.fasta --out_file ransetiresults.txt --num_threads 4

**Comment by jrober84** [comment]
There was a hard limit of n=1 thread placed on some processes due to issues with tblastn with higher thread counts. This restriction has been removed and the new pending release will use all threads specified
